# see https://dependabot.com/docs/config-file/
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - "nadnoslen"
    allowed_updates:
      - match:
          update_type: all
          dependency_type: direct
      - match:
          update_type: security
          dependency_type: indirect
    #    automerged_updates: []
    #    default_assignees: []
    default_labels:
      - dependencies
    #    ignored_updates: []
    target_branch: master
    version_requirement_updates: auto
